version: '3.1'

services:
        frontend:
                container_name: frontend
                depends_on:
                        - db
                        - backend
                image: frontend
                build:
                        context: ./frontend
                        dockerfile: ./frontend/frontend.dockerfile
                ports:
                        - "8081:80"  
        backend:
                container_name: backend
                depends_on: 
                        - db
                image: backend
                build:
                        context: ./backend
                        dockerfile: ./backend/dockerfile
                ports:
                        - "5000:5000"      
        db:
                container_name: mysqldb
                restart: always
                image: mysql:latest
                ports:
                        - "3308:3306"
                environment:
                        MYSQL_ROOT_PASSWORD: '12345'
                volumes:
                        - dbvolume:/var/lib/mysql
volumes:
        dbvolume: