version: '2.1'

services:
        backend:
                container_name: backend
                image: backend
                build: .
                ports:
                        - 5000:5000   